// app/lib/presupuestos/demo.ts
// 15 presupuestos, 5 doctores, 2 clínicas — nuevos 6 estados.

import type { Presupuesto, Contacto, Doctor } from "./types";
import { computeUrgencyScore } from "./urgency";

const today = new Date();
function ago(n: number): string {
  const d = new Date(today);
  d.setDate(d.getDate() - n);
  return d.toISOString().slice(0, 10);
}

export const DEMO_DOCTORES: Doctor[] = [
  { id: "dr1", nombre: "Dr. García",    especialidad: "General",        clinica: "Clínica Madrid Centro", activo: true },
  { id: "dr2", nombre: "Dr. Martínez",  especialidad: "Implantólogo",   clinica: "Clínica Madrid Centro", activo: true },
  { id: "dr3", nombre: "Dra. Romero",   especialidad: "Ortodoncia",     clinica: "Clínica Madrid Centro", activo: true },
  { id: "dr4", nombre: "Dr. Sánchez",   especialidad: "Prostodoncista", clinica: "Clínica Salamanca",     activo: true },
  { id: "dr5", nombre: "Dra. López",    especialidad: "Endodoncista",   clinica: "Clínica Salamanca",     activo: true },
];

const raw: Omit<Presupuesto, "urgencyScore">[] = [
  // ── PRESENTADO (2) ──────────────────────────────────────────────
  {
    id: "p1",
    patientName: "Pedro Alonso Torres",
    patientPhone: "+34611100012",
    treatments: ["Revisión ortodoncia"],
    doctor: "Dra. Romero",
    doctorEspecialidad: "Ortodoncia",
    tipoPaciente: "Privado",
    tipoVisita: "Paciente con Historia",
    amount: 150,
    estado: "PRESENTADO",
    fechaPresupuesto: ago(2),
    fechaAlta: ago(2),
    daysSince: 2,
    clinica: "Clínica Madrid Centro",
    contactCount: 0,
    createdBy: "ventas@demo.com",
  },
  {
    id: "p2",
    patientName: "Laura Gómez Blanco",
    patientPhone: "+34611100011",
    treatments: ["Limpieza dental"],
    doctor: "Dr. García",
    doctorEspecialidad: "General",
    tipoPaciente: "Adeslas",
    tipoVisita: "Paciente con Historia",
    amount: 120,
    estado: "PRESENTADO",
    fechaPresupuesto: ago(4),
    fechaAlta: ago(4),
    daysSince: 4,
    clinica: "Clínica Salamanca",
    contactCount: 0,
    createdBy: "demo@fyllio.com",
  },
  // ── INTERESADO (3) ──────────────────────────────────────────────
  {
    id: "p3",
    patientName: "María García López",
    patientPhone: "+34611100001",
    treatments: ["Implante dental", "Corona cerámica"],
    doctor: "Dr. Martínez",
    doctorEspecialidad: "Implantólogo",
    tipoPaciente: "Privado",
    tipoVisita: "Primera Visita",
    amount: 2800,
    estado: "INTERESADO",
    fechaPresupuesto: ago(18),
    fechaAlta: ago(18),
    daysSince: 18,
    clinica: "Clínica Madrid Centro",
    notes: "Muy interesada, pide cita para confirmar",
    lastContactDate: ago(5),
    lastContactDaysAgo: 5,
    contactCount: 2,
    createdBy: "ventas@demo.com",
  },
  {
    id: "p4",
    patientName: "Carmen Sánchez Torres",
    patientPhone: "+34611100003",
    treatments: ["Ortodoncia invisible"],
    doctor: "Dra. Romero",
    doctorEspecialidad: "Ortodoncia",
    tipoPaciente: "Adeslas",
    tipoVisita: "Primera Visita",
    amount: 4200,
    estado: "INTERESADO",
    fechaPresupuesto: ago(21),
    fechaAlta: ago(21),
    daysSince: 21,
    clinica: "Clínica Madrid Centro",
    lastContactDate: ago(12),
    lastContactDaysAgo: 12,
    contactCount: 3,
    createdBy: "ventas@demo.com",
  },
  {
    id: "p5",
    patientName: "Roberto Fernández Gil",
    patientPhone: "+34611100009",
    treatments: ["Prótesis dental superior"],
    doctor: "Dr. Sánchez",
    doctorEspecialidad: "Prostodoncista",
    tipoPaciente: "Privado",
    tipoVisita: "Paciente con Historia",
    amount: 3600,
    estado: "INTERESADO",
    fechaPresupuesto: ago(7),
    fechaAlta: ago(7),
    daysSince: 7,
    clinica: "Clínica Salamanca",
    lastContactDate: ago(2),
    lastContactDaysAgo: 2,
    contactCount: 1,
    createdBy: "ventas@demo.com",
  },
  // ── EN_DUDA (2) ─────────────────────────────────────────────────
  {
    id: "p6",
    patientName: "Lucía Pérez Moreno",
    patientPhone: "+34611100007",
    treatments: ["Carillas de porcelana"],
    doctor: "Dr. García",
    doctorEspecialidad: "General",
    tipoPaciente: "Privado",
    tipoVisita: "Primera Visita",
    amount: 3200,
    estado: "EN_DUDA",
    fechaPresupuesto: ago(14),
    fechaAlta: ago(14),
    daysSince: 14,
    clinica: "Clínica Madrid Centro",
    notes: "Tiene miedo al dolor, necesita seguridad",
    lastContactDate: ago(3),
    lastContactDaysAgo: 3,
    contactCount: 4,
    createdBy: "ventas@demo.com",
  },
  {
    id: "p7",
    patientName: "Antonio López Ruiz",
    patientPhone: "+34611100004",
    treatments: ["Implante dental"],
    doctor: "Dr. Martínez",
    doctorEspecialidad: "Implantólogo",
    tipoPaciente: "Adeslas",
    tipoVisita: "Paciente con Historia",
    amount: 2800,
    estado: "EN_DUDA",
    fechaPresupuesto: ago(9),
    fechaAlta: ago(9),
    daysSince: 9,
    clinica: "Clínica Salamanca",
    notes: "Consulta cobertura Adeslas, pendiente confirmar",
    lastContactDate: ago(1),
    lastContactDaysAgo: 1,
    contactCount: 2,
    createdBy: "ventas@demo.com",
  },
  // ── EN_NEGOCIACION (2) ──────────────────────────────────────────
  {
    id: "p8",
    patientName: "Isabel Rodríguez Vega",
    patientPhone: "+34611100005",
    treatments: ["Blanqueamiento dental", "Carillas"],
    doctor: "Dr. García",
    doctorEspecialidad: "General",
    tipoPaciente: "Privado",
    tipoVisita: "Primera Visita",
    amount: 2400,
    estado: "EN_NEGOCIACION",
    fechaPresupuesto: ago(12),
    fechaAlta: ago(12),
    daysSince: 12,
    clinica: "Clínica Madrid Centro",
    notes: "Pide descuento o pago en cuotas",
    lastContactDate: ago(2),
    lastContactDaysAgo: 2,
    contactCount: 3,
    createdBy: "ventas@demo.com",
  },
  {
    id: "p9",
    patientName: "Francisco González Molina",
    patientPhone: "+34611100006",
    treatments: ["Ortodoncia invisible"],
    doctor: "Dra. Romero",
    doctorEspecialidad: "Ortodoncia",
    tipoPaciente: "Privado",
    tipoVisita: "Paciente con Historia",
    amount: 3900,
    estado: "EN_NEGOCIACION",
    fechaPresupuesto: ago(16),
    fechaAlta: ago(16),
    daysSince: 16,
    clinica: "Clínica Madrid Centro",
    notes: "Quiere comparar con otra clínica, pide mejor precio",
    lastContactDate: ago(4),
    lastContactDaysAgo: 4,
    contactCount: 2,
    createdBy: "ventas@demo.com",
  },
  // ── ACEPTADO (3) ────────────────────────────────────────────────
  {
    id: "p10",
    patientName: "Miguel Pérez Jiménez",
    patientPhone: "+34611100008",
    treatments: ["Ortodoncia invisible"],
    doctor: "Dra. Romero",
    doctorEspecialidad: "Ortodoncia",
    tipoPaciente: "Privado",
    tipoVisita: "Primera Visita",
    amount: 4500,
    estado: "ACEPTADO",
    fechaPresupuesto: ago(30),
    fechaAlta: ago(30),
    daysSince: 30,
    clinica: "Clínica Madrid Centro",
    contactCount: 2,
    createdBy: "demo@fyllio.com",
  },
  {
    id: "p11",
    patientName: "Ana Martín Díaz",
    patientPhone: "+34611100002",
    treatments: ["Endodoncia molar"],
    doctor: "Dra. López",
    doctorEspecialidad: "Endodoncista",
    tipoPaciente: "Adeslas",
    tipoVisita: "Paciente con Historia",
    amount: 850,
    estado: "ACEPTADO",
    fechaPresupuesto: ago(28),
    fechaAlta: ago(28),
    daysSince: 28,
    clinica: "Clínica Salamanca",
    contactCount: 2,
    createdBy: "demo@fyllio.com",
  },
  {
    id: "p12",
    patientName: "José Sánchez Romero",
    patientPhone: "+34611100010",
    treatments: ["Implante dental"],
    doctor: "Dr. Martínez",
    doctorEspecialidad: "Implantólogo",
    tipoPaciente: "Privado",
    tipoVisita: "Primera Visita",
    amount: 2800,
    estado: "ACEPTADO",
    fechaPresupuesto: ago(45),
    fechaAlta: ago(45),
    daysSince: 45,
    clinica: "Clínica Madrid Centro",
    contactCount: 3,
    createdBy: "demo@fyllio.com",
  },
  // ── PERDIDO (3) ─────────────────────────────────────────────────
  {
    id: "p13",
    patientName: "Marta López Gil",
    treatments: ["Carillas de porcelana"],
    doctor: "Dr. García",
    doctorEspecialidad: "General",
    tipoPaciente: "Privado",
    tipoVisita: "Primera Visita",
    amount: 2400,
    estado: "PERDIDO",
    fechaPresupuesto: ago(60),
    fechaAlta: ago(60),
    daysSince: 60,
    clinica: "Clínica Madrid Centro",
    notes: "Se fue con otra clínica por precio",
    contactCount: 3,
    createdBy: "ventas@demo.com",
  },
  {
    id: "p14",
    patientName: "Carlos García Pardo",
    treatments: ["Implante dental"],
    doctor: "Dr. Martínez",
    doctorEspecialidad: "Implantólogo",
    tipoPaciente: "Privado",
    tipoVisita: "Primera Visita",
    amount: 2800,
    estado: "PERDIDO",
    fechaPresupuesto: ago(35),
    fechaAlta: ago(35),
    daysSince: 35,
    clinica: "Clínica Madrid Centro",
    notes: "Sin respuesta tras 3 seguimientos",
    contactCount: 3,
    createdBy: "ventas@demo.com",
  },
  {
    id: "p15",
    patientName: "Sofía Herrera Pons",
    patientPhone: "+34611100015",
    treatments: ["Ortodoncia invisible"],
    doctor: "Dra. Romero",
    doctorEspecialidad: "Ortodoncia",
    tipoPaciente: "Adeslas",
    tipoVisita: "Primera Visita",
    amount: 3900,
    estado: "PERDIDO",
    fechaPresupuesto: ago(42),
    fechaAlta: ago(42),
    daysSince: 42,
    clinica: "Clínica Salamanca",
    notes: "Precio demasiado alto según paciente",
    contactCount: 2,
    createdBy: "demo@fyllio.com",
  },
];

export const DEMO_PRESUPUESTOS: Presupuesto[] = raw.map((p) => ({
  ...p,
  urgencyScore: computeUrgencyScore({ ...p, urgencyScore: 0 }),
}));

export const DEMO_CONTACTOS: Contacto[] = [
  { id: "c1",  presupuestoId: "p3", tipo: "llamada",  resultado: "contestó",     fechaHora: `${ago(18)}T09:30:00`, nota: "Primera llamada, muy interesada", registradoPor: "ventas@demo.com" },
  { id: "c2",  presupuestoId: "p3", tipo: "whatsapp", resultado: "no contestó",  fechaHora: `${ago(5)}T11:00:00`,  registradoPor: "ventas@demo.com" },
  { id: "c3",  presupuestoId: "p4", tipo: "llamada",  resultado: "contestó",     fechaHora: `${ago(21)}T10:00:00`, nota: "Interesada, pide tiempo para pensarlo", registradoPor: "ventas@demo.com" },
  { id: "c4",  presupuestoId: "p4", tipo: "whatsapp", resultado: "no contestó",  fechaHora: `${ago(14)}T10:30:00`, registradoPor: "ventas@demo.com" },
  { id: "c5",  presupuestoId: "p4", tipo: "llamada",  resultado: "pidió tiempo", fechaHora: `${ago(12)}T16:00:00`, nota: "Quiere consultar con su marido", registradoPor: "ventas@demo.com" },
  { id: "c6",  presupuestoId: "p5", tipo: "llamada",  resultado: "acordó cita",  fechaHora: `${ago(2)}T09:00:00`,  nota: "Cita para el viernes", registradoPor: "ventas@demo.com" },
  { id: "c7",  presupuestoId: "p6", tipo: "llamada",  resultado: "contestó",     fechaHora: `${ago(14)}T10:00:00`, nota: "Tiene miedo, necesita más información", registradoPor: "ventas@demo.com" },
  { id: "c8",  presupuestoId: "p6", tipo: "email",    resultado: "contestó",     fechaHora: `${ago(10)}T12:00:00`, nota: "Enviamos folleto explicativo del proceso", registradoPor: "ventas@demo.com" },
  { id: "c9",  presupuestoId: "p6", tipo: "llamada",  resultado: "pidió tiempo", fechaHora: `${ago(7)}T11:00:00`,  registradoPor: "ventas@demo.com" },
  { id: "c10", presupuestoId: "p6", tipo: "whatsapp", resultado: "no contestó",  fechaHora: `${ago(3)}T09:30:00`,  registradoPor: "ventas@demo.com" },
  { id: "c11", presupuestoId: "p7", tipo: "llamada",  resultado: "contestó",     fechaHora: `${ago(9)}T16:00:00`,  nota: "Consulta cobertura Adeslas", registradoPor: "ventas@demo.com" },
  { id: "c12", presupuestoId: "p7", tipo: "llamada",  resultado: "contestó",     fechaHora: `${ago(1)}T10:00:00`,  nota: "Confirmamos cobertura parcial 40%", registradoPor: "ventas@demo.com" },
  { id: "c13", presupuestoId: "p8", tipo: "visita",   resultado: "pidió tiempo", fechaHora: `${ago(12)}T11:00:00`, nota: "Vino a visita, pide financiación", registradoPor: "ventas@demo.com" },
  { id: "c14", presupuestoId: "p8", tipo: "email",    resultado: "contestó",     fechaHora: `${ago(6)}T09:00:00`,  nota: "Enviamos opciones de pago fraccionado", registradoPor: "ventas@demo.com" },
  { id: "c15", presupuestoId: "p8", tipo: "llamada",  resultado: "pidió tiempo", fechaHora: `${ago(2)}T16:00:00`,  nota: "Sigue valorando, decisión la próxima semana", registradoPor: "ventas@demo.com" },
];
