// app/api/no-shows/dev/seed2/route.ts
// Seed multiclinica en 5 bloques.
// GET /api/no-shows/dev/seed2?bloque=1..5
// "Staff ID" y "Sillón ID" son campos computados → no los seteamos.
// Usamos Nombre único por registro para lookup en bloques posteriores.

import { NextResponse } from "next/server";
import { DateTime } from "luxon";
import { base } from "../../../../lib/airtable";

const ZONE   = "Europe/Madrid";
const MARKER = "SEED2_2026";

// ── Helpers ────────────────────────────────────────────────────────────────

function sleep(ms: number) { return new Promise(r => setTimeout(r, ms)); }

function firstStr(x: unknown): string {
  if (typeof x === "string") return x;
  if (Array.isArray(x) && typeof x[0] === "string") return x[0];
  return "";
}

/** Create a single record. */
async function createOne(tabla: string, fields: Record<string, unknown>): Promise<string> {
  const r = await (base(tabla as any).create(fields as any) as any);
  return r.id;
}

/** Create records in batches of 10 (Airtable limit). */
async function createBatch(tabla: string, fieldsList: Record<string, unknown>[]): Promise<string[]> {
  const ids: string[] = [];
  for (let i = 0; i < fieldsList.length; i += 10) {
    const batch = fieldsList.slice(i, i + 10);
    if (batch.length === 1) {
      const r = await (base(tabla as any).create(batch[0] as any) as any);
      ids.push(r.id);
    } else {
      const rs = await (base(tabla as any).create(
        batch.map(f => ({ fields: f })) as any,
      ) as any);
      for (const r of rs) ids.push(r.id);
    }
    if (i + 10 < fieldsList.length) await sleep(250);
  }
  return ids;
}

/**
 * Build { logicalId → airtableRecordId } from any table.
 * Uses "Clínica ID" / "Staff ID" / "Sillón ID" as keys.
 */
async function fetchIdMap(tabla: string, idField: string): Promise<Map<string, string>> {
  const recs = await (base(tabla as any).select({ fields: [idField] }).all() as any);
  const map = new Map<string, string>();
  for (const r of recs) {
    const val = firstStr(r.fields[idField]);
    if (val) map.set(val, r.id);
  }
  return map;
}

/**
 * Build { Nombre → { recId, autoId } } from Staff.
 * autoId = the "Staff ID" value auto-generated by Airtable.
 */
async function fetchStaffByName(): Promise<Map<string, { recId: string; autoId: string }>> {
  const recs = await (base("Staff" as any).select({ fields: ["Nombre", "Staff ID"] }).all() as any);
  const map = new Map<string, { recId: string; autoId: string }>();
  for (const r of recs) {
    const nombre = firstStr(r.fields["Nombre"]);
    const autoId = firstStr(r.fields["Staff ID"]);
    if (nombre) map.set(nombre, { recId: r.id, autoId });
  }
  return map;
}

/** Build { Nombre → recId } from Sillones. */
async function fetchSillonesByName(): Promise<Map<string, string>> {
  const recs = await (base("Sillones" as any).select({ fields: ["Nombre"] }).all() as any);
  const map = new Map<string, string>();
  for (const r of recs) {
    const nombre = firstStr(r.fields["Nombre"]);
    if (nombre) map.set(nombre, r.id);
  }
  return map;
}

// ── Catalog ────────────────────────────────────────────────────────────────

const CLINICAS_DATA = [
  { "Clínica ID": "CLINIC_001", "Nombre": "Clínica Madrid Centro" },
  { "Clínica ID": "CLINIC_002", "Nombre": "Clínica Barcelona Eixample" },
];

const STAFF_DATA = [
  { nombre: "Dr. Andrés Rojas",    clinicaId: "CLINIC_001", noShowRate: 0.10 },
  { nombre: "Dra. Paula Díaz",     clinicaId: "CLINIC_001", noShowRate: 0.18 },
  { nombre: "Dr. Mateo López",     clinicaId: "CLINIC_001", noShowRate: 0.25 },
  { nombre: "Recepción Madrid",    clinicaId: "CLINIC_001", noShowRate: 0    },
  { nombre: "Dra. Carmen Vidal",   clinicaId: "CLINIC_002", noShowRate: 0.12 },
  { nombre: "Dr. Jorge Puig",      clinicaId: "CLINIC_002", noShowRate: 0.16 },
  { nombre: "Recepción Barcelona", clinicaId: "CLINIC_002", noShowRate: 0    },
];

// Nombre único (incluye clínica) → no ambigüedad entre S1 Madrid y S1 Barcelona
const SILLONES_DATA = [
  { nombre: "Madrid S1",    clinicaId: "CLINIC_001" },
  { nombre: "Madrid S2",    clinicaId: "CLINIC_001" },
  { nombre: "Madrid S3",    clinicaId: "CLINIC_001" },
  { nombre: "Barcelona S1", clinicaId: "CLINIC_002" },
  { nombre: "Barcelona S2", clinicaId: "CLINIC_002" },
];

// Doctor (por Nombre) → Sillón Nombre
const DOC_SILLON: Record<string, string> = {
  "Dr. Andrés Rojas":  "Madrid S1",
  "Dra. Paula Díaz":   "Madrid S2",
  "Dr. Mateo López":   "Madrid S3",
  "Dra. Carmen Vidal": "Barcelona S1",
  "Dr. Jorge Puig":    "Barcelona S2",
};

// Doctores clínicos por clínica (sin recepcionistas)
const CLINICAL_MADRID    = ["Dr. Andrés Rojas", "Dra. Paula Díaz", "Dr. Mateo López"];
const CLINICAL_BARCELONA = ["Dra. Carmen Vidal", "Dr. Jorge Puig"];

// ── Time params ────────────────────────────────────────────────────────────

const HIST_SLOTS_HOURS = [9, 11, 16];          // 3 slots/doctor/día
const HIST_DAYS        = [0, 1, 2, 3];          // Lun–Jue
const HIST_WEEKS = [
  "2026-02-16", "2026-02-23", "2026-03-02", "2026-03-09",
  "2026-03-16", "2026-03-23", "2026-03-30", "2026-04-06",
];

const FUTURE_SLOTS_HOURS = [9, 11, 16];         // 3 slots/doctor/día
const FUTURE_DAYS        = [0, 1, 2, 3, 4];     // Lun–Vie
const FUTURE_WEEKS       = ["2026-04-14", "2026-04-21"];

// ── Estado helpers ─────────────────────────────────────────────────────────

function histEstado(noShowRate: number, idx: number): "Cancelado" | "Completado" {
  return ((idx * 7 + 11) % 100) < Math.round(noShowRate * 100)
    ? "Cancelado"
    : "Completado";
}

function futureEstado(weekIdx: number, idx: number): string {
  const roll = (idx * 7 + 13) % 100;
  if (weekIdx === 0) {
    if (roll < 10) return "Cancelado";
    if (roll < 60) return "Confirmado";
    return "Agendado";
  }
  if (roll < 5)  return "Cancelado";
  if (roll < 25) return "Confirmado";
  return "Agendado";
}

// ── BLOQUE 1: Clínicas ─────────────────────────────────────────────────────

async function bloque1() {
  const created: { logicalId: string; nombre: string; recId: string }[] = [];
  for (const fields of CLINICAS_DATA) {
    const recId = await createOne("Clínicas", fields);
    created.push({ logicalId: fields["Clínica ID"], nombre: fields["Nombre"], recId });
    await sleep(250);
  }
  return { bloque: 1, created: created.length, records: created };
}

// ── BLOQUE 2: Staff ────────────────────────────────────────────────────────

async function bloque2() {
  const clinicaMap = await fetchIdMap("Clínicas", "Clínica ID");
  const created: unknown[] = [];

  for (const s of STAFF_DATA) {
    const fields: Record<string, unknown> = { "Nombre": s.nombre };
    const clinicaRecId = clinicaMap.get(s.clinicaId);
    if (clinicaRecId) fields["Clínica"] = [clinicaRecId];

    const recId = await createOne("Staff", fields);
    created.push({ nombre: s.nombre, clinicaId: s.clinicaId, recId });
    await sleep(250);
  }

  // Leer de vuelta para obtener los Staff IDs auto-generados
  const staffBack = await fetchStaffByName();
  const staffIds: Record<string, string> = {};
  for (const [nombre, info] of staffBack) {
    staffIds[nombre] = info.autoId;
  }

  return { bloque: 2, created: created.length, staffIdsGenerados: staffIds, records: created };
}

// ── BLOQUE 3: Sillones ─────────────────────────────────────────────────────

async function bloque3() {
  const clinicaMap = await fetchIdMap("Clínicas", "Clínica ID");
  const created: unknown[] = [];

  for (const s of SILLONES_DATA) {
    const fields: Record<string, unknown> = { "Nombre": s.nombre };
    const clinicaRecId = clinicaMap.get(s.clinicaId);
    if (clinicaRecId) fields["Clínica"] = [clinicaRecId];

    const recId = await createOne("Sillones", fields);
    created.push({ nombre: s.nombre, clinicaId: s.clinicaId, recId });
    await sleep(250);
  }

  return { bloque: 3, created: created.length, records: created };
}

// ── BLOQUE 4: Historial de citas (8 semanas) ───────────────────────────────

async function bloque4() {
  const clinicaMap  = await fetchIdMap("Clínicas", "Clínica ID");
  const staffByName = await fetchStaffByName();
  const sillonByName = await fetchSillonesByName();

  const tratRecs  = await (base("Tratamientos" as any).select({ fields: ["Nombre"] }).all() as any);
  const tratIds: string[]   = tratRecs.map((r: any) => r.id);
  const tratNames: string[] = tratRecs.map((r: any) => firstStr(r.fields["Nombre"]) || "Tratamiento");

  const pacRecs = await (base("Pacientes" as any).select({ maxRecords: 30, fields: [] }).all() as any);
  const pacIds: string[] = pacRecs.map((r: any) => r.id);

  if (!pacIds.length) throw new Error("Sin pacientes.");
  if (!tratIds.length) throw new Error("Sin tratamientos.");

  const records: Record<string, unknown>[] = [];
  let globalIdx = 0;

  for (const weekMon of HIST_WEEKS) {
    const monDt = DateTime.fromISO(weekMon, { zone: ZONE });

    for (const clinicDoctors of [CLINICAL_MADRID, CLINICAL_BARCELONA]) {
      const isBarcelona  = clinicDoctors === CLINICAL_BARCELONA;
      const clinicaId    = isBarcelona ? "CLINIC_002" : "CLINIC_001";
      const clinicaRecId = clinicaMap.get(clinicaId);
      if (!clinicaRecId) continue;

      for (const dayOffset of HIST_DAYS) {
        const dayDt = monDt.plus({ days: dayOffset });

        for (const doctorNombre of clinicDoctors) {
          const staffInfo   = staffByName.get(doctorNombre);
          const sillonNom   = DOC_SILLON[doctorNombre];
          const sillonRecId = sillonNom ? sillonByName.get(sillonNom) : undefined;
          if (!staffInfo) continue;

          const staffMeta = STAFF_DATA.find(s => s.nombre === doctorNombre)!;

          for (const hour of HIST_SLOTS_HOURS) {
            const startDt = dayDt.set({ hour, minute: 0, second: 0 });
            const durMin  = hour === 9 ? 60 : 45;
            const endDt   = startDt.plus({ minutes: durMin });

            const estado   = histEstado(staffMeta.noShowRate, globalIdx);
            const isNoShow = estado === "Cancelado";
            const tratIdx  = globalIdx % tratIds.length;
            const pacIdx   = globalIdx % pacIds.length;

            const fields: Record<string, unknown> = {
              "Nombre":      `${tratNames[tratIdx]} · Paciente ${pacIdx + 1}`,
              "Hora inicio": startDt.toUTC().toISO(),
              "Hora final":  endDt.toUTC().toISO(),
              "Estado":      estado,
              "Notas":       isNoShow ? `[NO_SHOW] ${MARKER}` : MARKER,
              "Clínica":     [clinicaRecId],
              "Profesional": [staffInfo.recId],
              "Tratamiento": [tratIds[tratIdx]],
              "Paciente":    [pacIds[pacIdx]],
            };
            if (sillonRecId) fields["Sillón"] = [sillonRecId];
            records.push(fields);
            globalIdx++;
          }
        }
      }
    }
  }

  const ids = await createBatch("Citas", records);
  return {
    bloque: 4,
    created: ids.length,
    semanas: HIST_WEEKS.length,
    tratamientos: [...new Set(tratNames)],
  };
}

// ── BLOQUE 5: Agenda activa (2 semanas futuras) ────────────────────────────

async function bloque5() {
  const clinicaMap   = await fetchIdMap("Clínicas", "Clínica ID");
  const staffByName  = await fetchStaffByName();
  const sillonByName = await fetchSillonesByName();

  const tratRecs  = await (base("Tratamientos" as any).select({ fields: ["Nombre"] }).all() as any);
  const tratIds: string[]   = tratRecs.map((r: any) => r.id);
  const tratNames: string[] = tratRecs.map((r: any) => firstStr(r.fields["Nombre"]) || "Tratamiento");

  const pacRecs = await (base("Pacientes" as any).select({ maxRecords: 30, fields: [] }).all() as any);
  const pacIds: string[] = pacRecs.map((r: any) => r.id);

  if (!pacIds.length) throw new Error("Sin pacientes.");
  if (!tratIds.length) throw new Error("Sin tratamientos.");

  const records: Record<string, unknown>[] = [];
  let globalIdx = 0;
  let skipped   = 0;

  for (let weekIdx = 0; weekIdx < FUTURE_WEEKS.length; weekIdx++) {
    const monDt = DateTime.fromISO(FUTURE_WEEKS[weekIdx], { zone: ZONE });

    for (const clinicDoctors of [CLINICAL_MADRID, CLINICAL_BARCELONA]) {
      const isBarcelona  = clinicDoctors === CLINICAL_BARCELONA;
      const clinicaId    = isBarcelona ? "CLINIC_002" : "CLINIC_001";
      const clinicaRecId = clinicaMap.get(clinicaId);
      if (!clinicaRecId) continue;

      let slotInClinic = 0;

      for (const dayOffset of FUTURE_DAYS) {
        const dayDt = monDt.plus({ days: dayOffset });

        for (const doctorNombre of clinicDoctors) {
          const staffInfo   = staffByName.get(doctorNombre);
          const sillonNom   = DOC_SILLON[doctorNombre];
          const sillonRecId = sillonNom ? sillonByName.get(sillonNom) : undefined;
          if (!staffInfo) continue;

          for (const hour of FUTURE_SLOTS_HOURS) {
            // Skip 1 of 15 → ~93% fill (close to 80% before cancellados)
            if (slotInClinic % 15 === 7) { slotInClinic++; skipped++; continue; }

            const startDt = dayDt.set({ hour, minute: 0, second: 0 });
            const durMin  = hour === 9 ? 60 : 45;
            const endDt   = startDt.plus({ minutes: durMin });

            const estado  = futureEstado(weekIdx, globalIdx);
            const tratIdx = globalIdx % tratIds.length;
            const pacIdx  = globalIdx % pacIds.length;

            const fields: Record<string, unknown> = {
              "Nombre":      `${tratNames[tratIdx]} · Paciente ${pacIdx + 1}`,
              "Hora inicio": startDt.toUTC().toISO(),
              "Hora final":  endDt.toUTC().toISO(),
              "Estado":      estado,
              "Notas":       MARKER,
              "Clínica":     [clinicaRecId],
              "Profesional": [staffInfo.recId],
              "Tratamiento": [tratIds[tratIdx]],
              "Paciente":    [pacIds[pacIdx]],
            };
            if (sillonRecId) fields["Sillón"] = [sillonRecId];
            records.push(fields);
            globalIdx++;
            slotInClinic++;
          }
        }
      }
    }
  }

  const ids = await createBatch("Citas", records);
  return { bloque: 5, created: ids.length, skipped };
}

// ── Router ─────────────────────────────────────────────────────────────────

export async function GET(req: Request) {
  const { searchParams } = new URL(req.url);
  const bloque = searchParams.get("bloque") ?? "";
  try {
    switch (bloque) {
      case "1": return NextResponse.json(await bloque1());
      case "2": return NextResponse.json(await bloque2());
      case "3": return NextResponse.json(await bloque3());
      case "4": return NextResponse.json(await bloque4());
      case "5": return NextResponse.json(await bloque5());
      default:
        return NextResponse.json({ error: "Parámetro bloque requerido: 1..5" }, { status: 400 });
    }
  } catch (e: any) {
    console.error(`[seed2 bloque ${bloque}]`, e);
    return NextResponse.json({ error: e?.message ?? "Error" }, { status: 500 });
  }
}
