// Sprint 13 Bloque 2 — Iconografia Lucide unificada.
// Re-export con stroke 1.5 por defecto. Usar SIZE_* para coherencia.

export {
  Sparkles,
  Bell,
  Phone,
  MessageCircle,
  ClipboardList,
  Pencil,
  RefreshCw,
  Check,
  X,
  ArrowUp,
  Wrench,
  AlertTriangle,
  ChevronRight,
  Search,
  Calendar,
  Clock,
  User,
  Users,
  Plus,
  Filter,
  TrendingUp,
  TrendingDown,
  Minus,
  // Sprint UI — set ampliado para sustituir emojis-como-UI en toda la app.
  Activity,
  AlertCircle,
  ArrowRight,
  Ban,
  BarChart3,
  BellRing,
  Bot,
  Brain,
  Building2,
  CalendarClock,
  CalendarDays,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  CircleDollarSign,
  ClipboardCheck,
  Copy,
  CreditCard,
  Download,
  Droplet,
  Euro,
  Eye,
  FileSpreadsheet,
  FileText,
  Flame,
  FolderOpen,
  Gauge,
  Hand,
  History,
  Hourglass,
  Inbox,
  Info,
  Layers,
  Lightbulb,
  ListChecks,
  LoaderCircle,
  Lock,
  Mail,
  MapPin,
  Megaphone,
  MessageSquare,
  Moon,
  PartyPopper,
  PhoneCall,
  Repeat,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  Sliders,
  SlidersHorizontal,
  Smartphone,
  Star,
  Stethoscope,
  StickyNote,
  Sun,
  Table,
  Tag,
  Target,
  Trash2,
  Upload,
  UserCheck,
  UserX,
  Wand2,
  XCircle,
  Zap,
} from "lucide-react";

/** Sizes coherentes — la decision de tamaño literal del brief se respeta
 *  por sitio de uso, pero estos defaults sirven de base. */
export const ICON_SIZE = {
  xs: 12,
  sm: 14,
  md: 16,
  lg: 20,
  xl: 22,
} as const;

/** Stroke uniforme 1.5 segun brief Sprint 13. */
export const ICON_STROKE = 1.5;
